### ISSUE TITLE
Inconsistent package name in API dependency

### ISSUE THREAD

**Issue by MagmaBlock** [4drian3d/AuthMeVelocity#111]
I noticed that your GitHub username seems changed, which led to an inconsistency in the package name of the library's dependency. The current package name in the Maven repository is "io.github.4drian3d", but the actual jar file still contains the package name as "io.github._4drian3d".

Dependency information in wiki also wrong: https://github.com/4drian3d/AuthMeVelocity/wiki/Plugin-API

This inconsistency is causing issues when trying to use the library in my project, as the IDE cannot properly resolve the package names.

**Comment by 4drian3d** [comment]
> I noticed that your GitHub username seems changed, which led to an inconsistency in the package name of the library's dependency. The current package name in the Maven repository is "io.github.4drian3d", but the actual jar file still contains the package name as "io.github._4drian3d".
> 
> Dependency information in wiki also wrong: https://github.com/4drian3d/AuthMeVelocity/wiki/Plugin-API
> 
> This inconsistency is causing issues when trying to use the library in my project, as the IDE cannot properly resolve the package names.

Yes, I would have liked to have consistency in both the groupId and the package, but it is not possible because the domain that corresponds to me is `io.github.4drian3d`, but in Java it is not possible to assign a number as the initial character of a package, so, according to advice from developers who have already published libraries in Maven Central and according to documentation, I had to add an initial `_`(`io.github._4drian3d`). In my other projects like MiniPlaceholders I do have consistency in the groupId and in the package (`io.github.miniplaceholders`) since it does not contain numbers.
The bug about the documentation is already fixed, thanks for reporting.
