### ISSUE TITLE
Ability to require permission for send-on-login

### ISSUE THREAD

**Issue by RealTriassic** [4drian3d/AuthMeVelocity#125]
A new toggle could be added under `send-on-login` in the configuration called `require-permission` just like in [AuthMeVelocity Last Server Addon](https://github.com/4drian3d/AuthMeVelocity-LastServerAddon). The permission node could be `authmevelocity.send-on-login` or whatever else you decide on.

This would be useful for servers that require players to complete a test before being sent away from the login server.

**Comment by 4drian3d** [comment]
Specifically for that I implemented the PreSendOnLogin event, so that some external plugin can define the necessary conditions for AuthMeVelocity to send the player to the initial server https://javadoc.io/doc/io.github.4drian3d/authmevelocity-api-velocity/latest/io.github._4drian3d.authmevelocity.api.velocity/io/github/_4drian3d/authmevelocity/api/velocity/event/PreSendOnLoginEvent.html.
